### ISSUE TITLE
Support for vim-indent-guides

### ISSUE THREAD

**Issue by MindTooth** [roosta/vim-srcery#15]
Tried to add some basic colors to indent guide.  Thoughts?  Disregard the flashing red error, have fixed it ;)

Based on `xgrey2` & `xgrey3`.

<img width="1108" alt="screen shot 2018-05-11 at 17 08 12" src="https://user-images.githubusercontent.com/33870508/39931568-0e8dc9ae-553e-11e8-805b-212b0d421166.png">

**Comment by roosta** [comment]
I like it. Its visible but subtle. Those grays work well if used sparingly.

**Comment by MindTooth** [comment]
Good.  I'll submit a patch tomorrow.  Now my hands is broken after sitting with different terminal tweaks for almost 12 hours, so a break is in order :'(  Enjoy it a bunch though 👍

**Comment by roosta** [comment]
Thank you again for all the awesome work you do. Appreciate it immensely.
