### ISSUE TITLE
Terminal.app doesn't work on double-click in El Capitan 10.11.6

### ISSUE THREAD

**Issue by nocdib** [roosta/vim-srcery#5]
I got the "...PowerPC applications are no longer supported" message on double-click. Renamed the file to have a .terminal extension then opened it without issue.  Nice colorscheme. 👍🏾

**Comment by roosta** [comment]
Thanks :) I don't have access to a mac so I simply grabbed the export off terminal.sexy and never tested it. Would you agree that renaming the file to srcery.terminal would be a good idea or does it differ depending on the version of terminal you have?

**Comment by nocdib** [comment]
Sorry for the delay. Terminal.app is the name of the standard Mac Terminal application. The text file generated from terminal.sexy when you choose the format "Terminal.app" will automatically open a new terminal window with the specified color settings if you change the extension to .terminal and double-click it. In short, it would be a good idea to rename it.
