### ISSUE TITLE
Color scheme doesn't work with Guake terminal

### ISSUE THREAD

**Issue by christianheinrichs** [roosta/vim-srcery#7]
Hi,

first of all, thank you for creating the srcery colorscheme. It looks quite awesome.

However, even after executing the `guake.sh` script there seems to be a problem with the Guake terminal colors which can be seen here:
![Guake terminal - Vim srcery](https://i.cubeupload.com/Vyvyh5.png)

On my Gnome terminal it works as expected, if the `gnome_terminal.sh` has been executed and the profile `srcery` is selected:
![Gnome terminal - Vim srcery](https://i.cubeupload.com/QNn8J6.png)

Any idea what's causing this?

**Comment by roosta** [comment]
Hi and thanks :) I don't rightly know why it doesn't work for you. I tried running it myself and it I didn't have any issues. Do you have gconf installed? and does the script output any error messages?

**Comment by christianheinrichs** [comment]
@roosta I am running Debian Stretch on this machine and `dpkg -l | grep -i gconf` outputs this:

> ii  gconf-defaults-service                                      3.2.6-4+b1                                  amd64        GNOME configuration database system (system defaults service)
> ii  gconf-service                                               3.2.6-4+b1                                  amd64        GNOME configuration database system (D-Bus service)
> ii  gconf2                                                      3.2.6-4+b1                                  amd64        GNOME configuration database system (support tools)
> ii  gconf2-common                                               3.2.6-4                                     all          GNOME configuration database system (common files)
> ii  libgconf-2-4:amd64                                          3.2.6-4+b1                                  amd64        GNOME configuration database system (shared libraries)
> ii  libgconf2.0-cil                                             2.24.2-4                                    all          CLI binding for GConf 2.24
> ii  python-gconf                                                2.28.1+dfsg-1.2                             amd64        Python bindings for the GConf configuration database system

So I assume gconf is installed.

When I do `cd .vim/term_colors/ && ./guake.sh` the Guake terminal colors change and no errors are shown. However, as soon as I open the gnome_terminal.sh script with `vim gnome_terminal.sh` the same problem occurs, the colors are all wrong.

**Comment by roosta** [comment]
Try setting `set t_Co=256` in your .vimrc

**Comment by christianheinrichs** [comment]
@roosta Thank you!

That setting has fixed the problem, since the value before was `set t_Co=8`.
